language:
  - ruby 

before_install:
  - yes | gem update --system --force
  - gem install bundler
  - gem update --system
services:
  - postgresql

before_script:
  - psql -c 'create database stellar_BE_test;' -U postgres